About and Menu update - Resolves issue #31 copy about SS
erikpantzar/starting-strength pull request #46
Opened 2021-10-15 12:14 UTC by JoacimNilsen

Added text about SS and how the app works. Also defined texts to typography. Maybe, and maybe after you have a look we might do something about line height.

2021-10-15 12:27 UTC, erikpantzar requested changes
1. Make /about route
2. In the menu, make section 1 sentence "What is SS", and read more links to /about page
3. I think we should work more on the text

2021-10-19 10:23 UTC, JoacimNilsen commented
Could use some help with writing a statement or some other solution to make backdrop close upon clicking link. Spent some time on it but decided to move on to next issue!

2021-10-20 17:00 UTC, erikpantzar commented
> Could use some help with writing a statement or some other solution to make backdrop close upon clicking link. Spent some time on it but decided to move on to next issue!

Smart, will have lookise

2021-10-21 08:12 UTC, JoacimNilsen commented
I fixed the text with alot of <br /> and i dont think the code looks nice with all that. Do you have a suggestion to do it in another way or is it A-OK?

2021-10-21 12:17 UTC, erikpantzar requested changes

2021-10-21 12:17 UTC, erikpantzar commented on src/View/About.js
> +      <br />
`<br />` is if you want just one line break. If you want to split text into several different paragraphs, just split them up into separate paragraphs like so:

```
<Typography>
  Text goes here
 </Typography>

<Typography>
    Another pararaph
 </Typography>


<Typography variant="h2">
  I am a heading
</Typography>

<Typography>
  Here I go again being a paragraph. </ br>
  And this is another line that belongs to the same paragraph!
</Typography>

```

2021-10-22 12:11 UTC, JoacimNilsen commented on src/View/About.js
> +      <br />
Of course! On it!

2021-10-22 12:25 UTC, erikpantzar commented
Please push ur commits so I can see them here =) @JoacimNilsen

2021-10-22 14:38 UTC, closed without merging