Design workout cards
erikpantzar/starting-strength pull request #60
Opened 2021-10-27 08:21 UTC by JoacimNilsen

Resolves  issue #51 and implements the design I have been working on from the figma setup.
Went through it a few times to make sure it is all there, looking forward to be reviewed 🎈

2021-10-27 09:31 UTC, erikpantzar commented on src/Components/WorkoutList/WorkoutList.css
> +.workout {
Would like to have namespaced classNames:

`.WorkoutList-exercise`
`.WorkoutList-reps`
`.WorkoutList-weight`

2021-10-27 09:32 UTC, erikpantzar commented on src/Components/WorkoutList/WorkoutList.css
> +    font-size: 0px;
Is there even text inside of this?  (remove font-size)
We could actually piut text in here but then text-indent it to make it non visible, but maybe readable for blind people.

2021-10-27 09:55 UTC, JoacimNilsen commented on src/Components/WorkoutList/WorkoutList.css
> +    font-size: 0px;
Yeah, sorry! I was struggling a bit with CSS and that sorted it out for me while designing. Fixed!

2021-10-27 11:10 UTC, erikpantzar requested changes

2021-10-27 11:10 UTC, erikpantzar commented on src/Components/WorkoutList/WorkoutList.css
> +    font-size: 0px;
## Styles
```
.WorkoutList-status-icon {
   width: 6px; height: 6px;
   background: #00D1FF;
   border-radius: 50%;  
}
.WorkoutList-status-icon--isDone {
  background: #DB009E;
}
```

## Markup:
```
<div className={['WorkoutList-status-icon',   isDone && 'WorkoutList-status-icon--isDone'].join(' ')} />
```

2021-10-27 11:10 UTC, erikpantzar commented on src/Components/WorkoutList/WorkoutList.css
> +    position: absolute;
Please put these styles on the one I suggested earlier
`.WorkoutList-status-icon`

2021-10-27 11:10 UTC, erikpantzar commented on src/Components/WorkoutList/WorkoutList.js
> +              <span className="icon-done" />
Your variant works and looks good!  But please use markup similiar to what I proposed earlier.

2021-10-27 11:10 UTC, erikpantzar commented on src/Components/WorkoutList/doing-dot.svg
> +<svg width="13" height="13" viewBox="0 0 13 13" fill="none" xmlns="http://www.w3.org/2000/svg">
Please remove entire file

2021-10-27 11:10 UTC, erikpantzar commented on src/Components/WorkoutList/done-dot.svg
> +<svg width="13" height="13" viewBox="0 0 13 13" fill="none" xmlns="http://www.w3.org/2000/svg">
Please remove entire file

2021-10-27 11:10 UTC, erikpantzar commented on src/Components/WorkoutList/WorkoutList.css
> +    background: var(--color-main-cta);
Since all `WorkoutList-link` look the same, we could remove all of the `nth-child` things and use the base class and put all styles there.

2021-10-27 11:34 UTC, erikpantzar commented on src/Components/WorkoutList/WorkoutList.css
> +    background: var(--color-main-cta);
Could we update the modifier class (`workout__isDone`) to instead be the same as the original elements but just add the `--isDone`?

Example here would be:
```
.WorkoutList-link {} // base styles
.WorkoutList-link.WorkoutList-link--isDone {  } // state overrides
```

2021-11-01 15:09 UTC, erikpantzar approved these changes
Looks good! :)

2021-11-01 16:18 UTC, merged